version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    image: node:17-alpine3.14
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      PORT: 5000
    ports:
      - 5000:5000
    command: npm run dev

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080